rule = ${ (tag | text)+ }

tag = ${ "#" ~ (action)* ~ tagname ~ (modifier)* ~ "#" }

tagname = @{ (nonspecial)+ }

modifier = ${ "." ~ tagname }

text = ${ (nonhash)+ }

action = ${ "[" ~ tagname ~ ":" ~ (action_rhs)+ ~ "]" }
action_rhs = ${ (tag | action_text)+ }
action_text = ${ (action_char)+ }
action_char = _{ !("#" | "]") ~ ANY }

nonspecial = _{ !("#" | "[" | "]" | ":" | ".") ~ ANY }
nonhash = _{ !("#") ~ ANY }
